Traceback (most recent call last):
  File "/usr/share/miniconda/envs/foss4g/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/envs/foss4g/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda/envs/foss4g/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda/envs/foss4g/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda/envs/foss4g/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/envs/foss4g/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/envs/foss4g/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda/envs/foss4g/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
xr.open_dataset(fs.open(s3path),
                chunk=(15680,40320))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Input [0;32mIn [5][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m [43mxr[49m[38;5;241;43m.[39;49m[43mopen_dataset[49m[43m([49m[43mfs[49m[38;5;241;43m.[39;49m[43mopen[49m[43m([49m[43ms3path[49m[43m)[49m[43m,[49m
[1;32m      2[0m [43m                [49m[43mchunk[49m[38;5;241;43m=[39;49m[43m([49m[38;5;241;43m15680[39;49m[43m,[49m[38;5;241;43m40320[39;49m[43m)[49m[43m)[49m

File [0;32m/usr/share/miniconda/envs/foss4g/lib/python3.10/site-packages/xarray/backends/api.py:531[0m, in [0;36mopen_dataset[0;34m(filename_or_obj, engine, chunks, cache, decode_cf, mask_and_scale, decode_times, decode_timedelta, use_cftime, concat_characters, decode_coords, drop_variables, inline_array, backend_kwargs, **kwargs)[0m
[1;32m    519[0m decoders [38;5;241m=[39m _resolve_decoders_kwargs(
[1;32m    520[0m     decode_cf,
[1;32m    521[0m     open_backend_dataset_parameters[38;5;241m=[39mbackend[38;5;241m.[39mopen_dataset_parameters,
[0;32m   (...)[0m
[1;32m    527[0m     decode_coords[38;5;241m=[39mdecode_coords,
[1;32m    528[0m )
[1;32m    530[0m overwrite_encoded_chunks [38;5;241m=[39m kwargs[38;5;241m.[39mpop([38;5;124m"[39m[38;5;124moverwrite_encoded_chunks[39m[38;5;124m"[39m, [38;5;28;01mNone[39;00m)
[0;32m--> 531[0m backend_ds [38;5;241m=[39m [43mbackend[49m[38;5;241;43m.[39;49m[43mopen_dataset[49m[43m([49m
[1;32m    532[0m [43m    [49m[43mfilename_or_obj[49m[43m,[49m
[1;32m    533[0m [43m    [49m[43mdrop_variables[49m[38;5;241;43m=[39;49m[43mdrop_variables[49m[43m,[49m
[1;32m    534[0m [43m    [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mdecoders[49m[43m,[49m
[1;32m    535[0m [43m    [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m,[49m
[1;32m    536[0m [43m[49m[43m)[49m
[1;32m    537[0m ds [38;5;241m=[39m _dataset_from_backend_dataset(
[1;32m    538[0m     backend_ds,
[1;32m    539[0m     filename_or_obj,
[0;32m   (...)[0m
[1;32m    547[0m     [38;5;241m*[39m[38;5;241m*[39mkwargs,
[1;32m    548[0m )
[1;32m    549[0m [38;5;28;01mreturn[39;00m ds

[0;31mTypeError[0m: H5netcdfBackendEntrypoint.open_dataset() got an unexpected keyword argument 'chunk'
TypeError: H5netcdfBackendEntrypoint.open_dataset() got an unexpected keyword argument 'chunk'

